name:                frp-and-domain-modelling
version:             0.1.0.0
github:              "ibcoleman/frp-and-domain-modelling"
license:             BSD3
author:              "Ian Coleman"
maintainer:          "ibcoleman@gmail.com"
copyright:           "FOSS"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ibcoleman/frp-and-domain-modelling#readme>

dependencies:
- base >= 4.7 && < 5
- time

library:
  source-dirs: src

executables:
  frp-and-domain-modelling-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frp-and-domain-modelling

tests:
  frp-and-domain-modelling-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frp-and-domain-modelling
